# Generated by Django 4.1.3 on 2022-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_companyemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='return_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
