# Generated by Django 4.1.3 on 2022-11-13 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_log_return_condition_alter_log_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='checkout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
